# -*- coding: utf-8 -*-
"""run_orchestrator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12O5-4QTH5kTNzjY8ei9r55w0i9NMD689
"""

# run_orchestrator.py
from orchestrator import run_full_orchestrator

if __name__ == "__main__":
    print("🚀 Ejecutando Orquestador Completo...\n")
    signals_df, kpis, actions, log = run_full_orchestrator(verbose=True)

    print("\n" + "="*50)
    print("✅ RESULTADOS FINALES DEL ORQUESTADOR")
    print("="*50)
    print("LOG:", log)
    print("\nKPIs:", kpis)
    print("\nAcciones propuestas:")
    for a in actions:
        print(f"  - {a}")